name: k_chart
description: A Flutter K Chart.
version: 0.7.0
homepage: https://github.com/mafanwei/k_chart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: 4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
